# Generated by Django 4.2.4 on 2023-08-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='items_orgin',
            field=models.CharField(max_length=50),
        ),
    ]
