# Generated by Django 4.2.4 on 2023-08-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0002_sale_phone_number_alter_product_items_orgin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
