# Generated by Django 4.2.4 on 2023-08-09 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0003_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_arrvial',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
