# Generated by Django 4.2.4 on 2023-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0005_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='part_number',
            field=models.IntegerField(default=0),
        ),
    ]
