# Generated by Django 4.2.4 on 2023-08-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0006_sale_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='part_name',
            field=models.IntegerField(default=0),
        ),
    ]
