# Generated by Django 4.2.4 on 2023-08-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0009_product_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='branch_name',
        ),
    ]
