# Generated by Django 4.2.4 on 2023-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0010_remove_sale_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch_name',
        ),
    ]
