# Generated by Django 4.2.4 on 2023-08-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0014_rename_product_sparepart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='item_name',
            new_name='part_name',
        ),
    ]
