# Generated by Django 4.2.4 on 2023-08-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('total_quantity', models.IntegerField(default=0)),
                ('issued_quantity', models.IntegerField(default=0)),
                ('received_quantity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('items_orgin', models.IntegerField(max_length=50)),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('issued_to', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.product')),
            ],
        ),
    ]
