# Generated by Django 4.2.4 on 2023-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0007_sale_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
