# Generated by Django 4.2.4 on 2023-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0012_product_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
