# Generated by Django 4.2.4 on 2023-08-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0013_alter_product_branch_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='SparePart',
        ),
    ]
